### PR TITLE
feat: Added ability to add tar options

### PR DESCRIPTION
**Pull request by dhammma**
### Description of the Change

Added the ability to pass options to tar CLI to impact tar archive creation options

### Screenshot or Gif

N/A

### Applicable Issues

N/A

### CODE REVIEW

**Comment by dhammma** [comment]
Hi @Th3S4mur41 

I found this action very helpful. I need to have the possibility to add tar options for my private project pipelines. I don't have experience in contributing to open-source. Would be glad if you could assist if you see some concerns about my suggestion.

Thanks

**Comment by Th3S4mur41** [comment]
@dhammma Thanks for your contribution...
I'll have a look as soon as possible.

I also noticed that [your first PR was closed as invalid by the CI](https://github.com/eviden-actions/upload-artifact/pull/125).
I'll make sure to improve our CI to handle those kind of CI better in the future.

**Comment by Th3S4mur41** [comment]
@dhammma what kind of options are you looking to set?
I'm trying to figure out if maybe there is a better and more secure way to do it and if [download-artifact](https://github.com/eviden-actions/download-artifact) would be impacted too

**Comment by dhammma** [comment]
@Th3S4mur41 I want to use option -C, an example of how I want to use it:

```shell
tar -cf simple-app.tar -C project-components/backend/simple-app .
```

I initially thought about adding the specific option name for this tar flag, but I've struggled to choose the understandable name for input

**Comment by dhammma** [comment]
And, also I thought that probably someone else would desire to add more options

**Comment by Th3S4mur41** [comment]
Ok, you'd like to set the current working directory to something different than `.`
In that case I would rather suggest to add a new `cwd` input to set it.
This would match the [naming in node for a similar attribute](https://www.geeksforgeeks.org/node-js-process-cwd-method/).

This would also be safer

**Comment by dhammma** [comment]
@Th3S4mur41 it is not convenient for me because in this case tar is created in the wrong place for me

**Comment by Th3S4mur41** [comment]
Just to make it clear, the `cwd` was just a name proposal, it would still do the exact same thing you intend.
Alternatively, we could name the input `directory` which is the long name for the same function in the tar tool itself

> [!NOTE]
>     -C, --directory=DIR
              Change to DIR before performing any operations.  This
              option is order-sensitive, i.e. it affects all options
              that follow.

**Comment by Th3S4mur41** [comment]
Feature added as discussed in https://github.com/eviden-actions/upload-artifact/pull/131

**Pull request closed without merging**
